# Generated by Django 4.2.7 on 2025-12-11 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typing_practice', '0003_text_word_count_alter_codesnippet_id_alter_text_body_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('finished', 'Tugallangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=10)),
                ('mode', models.CharField(choices=[('text', 'Matn'), ('code', 'Kod')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('code_snippet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typing_practice.codesnippet')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_battles', to=settings.AUTH_USER_MODEL)),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typing_practice.text')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('mistakes', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='battles.battle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-wpm'],
                'unique_together': {('battle', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['status', '-created_at'], name='battles_bat_status_81aea0_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['creator', 'status'], name='battles_bat_creator_22dbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['opponent', 'status'], name='battles_bat_opponen_435b02_idx'),
        ),
    ]
