# Generated by Django 4.2.7 on 2025-12-29 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='battle_type',
            field=models.CharField(choices=[('speed', 'Tezlik'), ('accuracy', 'Aniqlik'), ('endurance', 'Chidamlilik'), ('balanced', 'Muvozanatli')], default='balanced', help_text='Jang turi', max_length=20),
        ),
        migrations.AddField(
            model_name='battle',
            name='countdown_seconds',
            field=models.IntegerField(default=3, help_text='Countdown (soniya)'),
        ),
        migrations.AddField(
            model_name='battle',
            name='is_auto_match',
            field=models.BooleanField(default=False, help_text='Avtomatik matchmaking orqali yaratilgan'),
        ),
        migrations.AddField(
            model_name='battle',
            name='rematch_of',
            field=models.ForeignKey(blank=True, help_text="Qaysi jangning rematch'i", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematches', to='battles.battle'),
        ),
        migrations.AddField(
            model_name='battle',
            name='time_limit_seconds',
            field=models.IntegerField(default=300, help_text='Vaqt limiti (soniya)'),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='progress_percent',
            field=models.FloatField(default=0, help_text='Jarayon foizi (0-100)'),
        ),
        migrations.CreateModel(
            name='BattleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1000, help_text='ELO rating')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('win_streak', models.IntegerField(default=0)),
                ('best_win_streak', models.IntegerField(default=0)),
                ('total_battles', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['-rating'], name='battles_bat_rating_af64a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='BattleInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('expired', 'Muddati tugagan')], default='pending', max_length=10)),
                ('battle_mode', models.CharField(choices=[('text', 'Matn'), ('code', 'Kod')], default='text', max_length=10)),
                ('battle_type', models.CharField(choices=[('speed', 'Tezlik'), ('accuracy', 'Aniqlik'), ('endurance', 'Chidamlilik'), ('balanced', 'Muvozanatli')], default='balanced', max_length=20)),
                ('time_limit_seconds', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Taklifning amal qilish muddati')),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='battles.battle')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_battle_invitations', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_battle_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['to_user', 'status'], name='battles_bat_to_user_5d1db7_idx'), models.Index(fields=['from_user', 'status'], name='battles_bat_from_us_57136e_idx')],
            },
        ),
    ]
