# Generated by Django 4.2.7 on 2025-12-29 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_userprofile_address_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', help_text='Emoji yoki icon', max_length=50)),
                ('badge_type', models.CharField(choices=[('speed', 'Tezlik'), ('accuracy', 'Aniqlik'), ('streak', 'Ketma-ketlik'), ('milestone', 'Yutuq'), ('competition', 'Musobaqa'), ('consistency', 'Izchillik')], max_length=20)),
                ('requirement', models.JSONField(default=dict, help_text="Talablar (masalan: {'wpm': 100, 'sessions': 50})")),
                ('xp_reward', models.IntegerField(default=50, help_text='XP mukofoti')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['badge_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Joriy ketma-ketlik (kun)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_practice_date',
            field=models.DateField(blank=True, help_text='Oxirgi mashq qilgan sana', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Eng uzun ketma-ketlik'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_practice_days',
            field=models.IntegerField(default=0, help_text='Jami mashq qilgan kunlar'),
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_xp', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=100, help_text='Progress foizi (0-100)')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='accounts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('badge', 'Badge'), ('level_up', 'Level Up'), ('challenge', 'Challenge'), ('competition', 'Musobaqa'), ('battle', 'Battle'), ('streak', 'Streak'), ('achievement', 'Yutuq'), ('system', 'Tizim')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='🔔', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('challenge_type', models.CharField(choices=[('speed', 'Tezlik'), ('accuracy', 'Aniqlik'), ('code', 'Kod'), ('text', 'Matn'), ('consistency', 'Izchillik')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_wpm', models.IntegerField(blank=True, null=True)),
                ('target_accuracy', models.FloatField(blank=True, null=True)),
                ('target_sessions', models.IntegerField(blank=True, default=1, null=True)),
                ('reward_xp', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'is_active'], name='accounts_da_date_e00e23_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('result_wpm', models.FloatField(blank=True, null=True)),
                ('result_accuracy', models.FloatField(blank=True, null=True)),
                ('xp_earned', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='accounts.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['badge_type', 'is_active'], name='accounts_ba_badge_t_af62d9_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', '-earned_at'], name='accounts_us_user_id_d15dcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='accounts_no_user_id_b37b35_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx'),
        ),
        migrations.AddIndex(
            model_name='challengecompletion',
            index=models.Index(fields=['user', '-completed_at'], name='accounts_ch_user_id_6810b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengecompletion',
            unique_together={('user', 'challenge')},
        ),
    ]
