# Generated by Django 5.0.1 on 2026-01-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_badge_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='rarity',
            field=models.CharField(choices=[('common', 'Oddiy'), ('rare', 'Noyob'), ('epic', 'Epik'), ('legendary', 'Afsonaviy')], default='common', help_text='Badge noyobligi', max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='rarity_color',
            field=models.CharField(default='#6b7280', help_text='Hex color for rarity', max_length=20),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='progress_history',
            field=models.JSONField(blank=True, default=list, help_text='Progress tarixi'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('speed', 'Tezlik'), ('accuracy', 'Aniqlik'), ('streak', 'Ketma-ketlik'), ('milestone', 'Yutuq'), ('competition', 'Musobaqa'), ('consistency', 'Izchillik'), ('battle', 'Jang'), ('special', 'Maxsus')], max_length=20),
        ),
    ]
