# Generated by Django 5.0.1 on 2026-01-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_badge_rarity_badge_rarity_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='generated_password',
            field=models.CharField(blank=True, help_text="Google orqali ro'yxatdan o'tganda generatsiya qilingan parol (vaqtincha)", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_google_account',
            field=models.BooleanField(default=False, help_text="Google orqali ro'yxatdan o'tgan"),
        ),
    ]
