"""
Django settings for typing_platform project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / '.env')

# Ensure log directory exists
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)


def get_env_variable(var_name, default=None):
    """Get environment variable or return default/raise exception"""
    try:
        return os.environ[var_name]
    except KeyError:
        if default is not None:
            return default
        error_msg = f"Set the {var_name} environment variable"
        raise ImproperlyConfigured(error_msg)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable('SECRET_KEY', 'django-insecure-dev-key-change-in-production-ivzkh8b)o-te_f-ze%b_0i+p_^b)!l^2b+6qp(j9oj&363aw4%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_variable('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS - production'da domain nomlarini belgilang
ALLOWED_HOSTS_STR = get_env_variable('ALLOWED_HOSTS', '*')
if ALLOWED_HOSTS_STR == '*':
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',')]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # allauth uchun kerak
    
    # allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # captcha (django-simple-captcha)
    'captcha',
    
    'accounts',
    'typing_practice',
    'competitions',
    'leaderboard',
    'battles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Allauth middleware
    'typing_platform.middleware.ActiveUserMiddleware',
    'typing_platform.middleware.NoCacheMiddleware',  # HTML sahifalar uchun cache'ni o'chirish
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'typing_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'typing_platform.context_processors.online_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'typing_platform.wsgi.application'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL yoki SQLite - environment variable orqali tanlash
DB_ENGINE = get_env_variable('DB_ENGINE', 'django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': get_env_variable('DB_NAME'),
            'USER': get_env_variable('DB_USER'),
            'PASSWORD': get_env_variable('DB_PASSWORD'),
            'HOST': get_env_variable('DB_HOST', 'localhost'),
            'PORT': get_env_variable('DB_PORT', '5432'),
        }
    }
else:
    # Default SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Security settings
# Development settings (commented out for local development)
# Uncomment these for production deployment
if DEBUG:
    # Development: Allow HTTP
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    # Production: Force HTTPS
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Caching
# Production uchun Redis tavsiya qilinadi, lekin LocMemCache ham ishlaydi
CACHE_BACKEND = get_env_variable('CACHE_BACKEND', 'locmem')

if CACHE_BACKEND == 'redis':
    try:
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': get_env_variable('REDIS_URL', 'redis://127.0.0.1:6379/1'),
                'TIMEOUT': 300,  # 5 minutes
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                }
            }
        }
    except ImportError:
        # Redis library yo'q bo'lsa, LocMemCache ishlatiladi
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'unique-snowflake',
                'TIMEOUT': 300,
                'OPTIONS': {
                    'MAX_ENTRIES': 1000
                }
            }
        }
else:
    # Default LocMemCache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 300,  # 5 minutes
            'OPTIONS': {
                'MAX_ENTRIES': 1000
            }
        }
    }

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(LOG_DIR / 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'typing_platform': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'allauth': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

LOGIN_URL = 'accounts:login'  # Custom login (allauth emas)
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

# SITE_ID - allauth uchun kerak
SITE_ID = 1

# AUTHENTICATION_BACKENDS - allauth qo'shish
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth
]

# Allauth sozlamalari
ACCOUNT_LOGIN_METHODS = {'email', 'username'}  # Email yoki username bilan kirish
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']  # Ro'yxatdan o'tish maydonlari
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # 'mandatory', 'optional', yoki 'none'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_LOGOUT_ON_GET = True

# Google OAuth dan keyin qayerga o'tish
ACCOUNT_SIGNUP_REDIRECT_URL = 'dashboard'  # Yangi user ro'yxatdan o'tganda
ACCOUNT_LOGIN_REDIRECT_URL = 'dashboard'   # Login qilganda

# Social account sozlamalari
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,  # Security uchun
        'APP': {
            'client_id': get_env_variable('GOOGLE_CLIENT_ID', ''),
            'secret': get_env_variable('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        }
    }
}

# Custom adapters
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'
ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True  # Avtomatik ro'yxatdan o'tish (tasdiqlash sahifasini o'tkazib yuborish)
SOCIALACCOUNT_QUERY_EMAIL = True  # Email so'rash
SOCIALACCOUNT_EMAIL_REQUIRED = True  # Email majburiy
SOCIALACCOUNT_STORE_TOKENS = True  # Token'larni saqlash
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
# Continue page'ni o'tkazib yuborish (to'g'ridan-to'g'ri redirect)
SOCIALACCOUNT_LOGIN_ON_GET = True  # GET request'da avtomatik login qilish (sahifani o'tkazib yuborish)

# Email sozlamalari
# Development uchun console backend (terminal'da ko'rsatadi)
# Production uchun SMTP sozlamalarini qo'shing
EMAIL_BACKEND = get_env_variable('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# SMTP sozlamalari (Production uchun)
# Quyidagilarni .env faylga qo'shing:
# Gmail misoli:
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_USE_SSL=False
# EMAIL_HOST_USER=your-email@gmail.com
# EMAIL_HOST_PASSWORD=your-app-password
# DEFAULT_FROM_EMAIL=your-email@gmail.com
# SERVER_EMAIL=your-email@gmail.com
#
# Yandex misoli:
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST=smtp.yandex.ru
# EMAIL_PORT=465
# EMAIL_USE_TLS=False
# EMAIL_USE_SSL=True
# EMAIL_HOST_USER=your-email@ya.ru
# EMAIL_HOST_PASSWORD=your-app-password
# DEFAULT_FROM_EMAIL=your-email@ya.ru
# SERVER_EMAIL=your-email@ya.ru

if EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
    EMAIL_HOST = get_env_variable('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(get_env_variable('EMAIL_PORT', '587'))
    
    # TLS yoki SSL - environment variable orqali
    EMAIL_USE_TLS = get_env_variable('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_USE_SSL = get_env_variable('EMAIL_USE_SSL', 'False') == 'True'
    
    # Agar ikkalasi ham True bo'lsa, faqat TLS ishlatiladi (Django default)
    # Yandex uchun port 465 va SSL kerak
    if EMAIL_USE_SSL:
        EMAIL_USE_TLS = False
    
    EMAIL_HOST_USER = get_env_variable('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = get_env_variable('EMAIL_HOST_PASSWORD', '')
    
    # DEFAULT_FROM_EMAIL va SERVER_EMAIL
    DEFAULT_FROM_EMAIL = get_env_variable('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
    SERVER_EMAIL = get_env_variable('SERVER_EMAIL', EMAIL_HOST_USER)

# Google reCAPTCHA sozlamalari (env'dan o'qing)
RECAPTCHA_PUBLIC_KEY = get_env_variable('RECAPTCHA_PUBLIC_KEY', '')
RECAPTCHA_PRIVATE_KEY = get_env_variable('RECAPTCHA_PRIVATE_KEY', '')
RECAPTCHA_REQUIRED_SCORE = float(get_env_variable('RECAPTCHA_REQUIRED_SCORE', '0.5')) if get_env_variable('RECAPTCHA_REQUIRED_SCORE', None) else None

# HTTPS uchun (production)
# if not DEBUG:
#     ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
