"""
Management command to create default badges
"""
from django.core.management.base import BaseCommand
from accounts.models import Badge


class Command(BaseCommand):
    help = 'Create default badges for gamification'

    def handle(self, *args, **options):
        badges_data = [
            # Speed badges
            {
                'name': 'Speed God',
                'description': '150+ WPM tezlikka erishish',
                'icon': '⚡⚡⚡',
                'badge_type': 'speed',
                'requirement': {'wpm': 150},
                'xp_reward': 300,
                'rarity': 'legendary',
                'rarity_color': '#ff6b00',
            },
            {
                'name': 'Speed Demon',
                'description': '120+ WPM tezlikka erishish',
                'icon': '⚡⚡',
                'badge_type': 'speed',
                'requirement': {'wpm': 120},
                'xp_reward': 200,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Speed Master',
                'description': '100+ WPM tezlikka erishish',
                'icon': '⚡',
                'badge_type': 'speed',
                'requirement': {'wpm': 100},
                'xp_reward': 100,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Speed Expert',
                'description': '80+ WPM tezlikka erishish',
                'icon': '🚀',
                'badge_type': 'speed',
                'requirement': {'wpm': 80},
                'xp_reward': 75,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Speed Advanced',
                'description': '60+ WPM tezlikka erishish',
                'icon': '💨',
                'badge_type': 'speed',
                'requirement': {'wpm': 60},
                'xp_reward': 50,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Speed Beginner',
                'description': '40+ WPM tezlikka erishish',
                'icon': '🐢',
                'badge_type': 'speed',
                'requirement': {'wpm': 40},
                'xp_reward': 25,
                'rarity': 'common',
                'rarity_color': '#6b7280',
            },
            
            # Accuracy badges
            {
                'name': 'Perfect Typist',
                'description': '100% aniqlik bilan 10 ta mashq',
                'icon': '💯',
                'badge_type': 'accuracy',
                'requirement': {'perfect_sessions': 10, 'accuracy': 100},
                'xp_reward': 150,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Accuracy Elite',
                'description': '98%+ o\'rtacha aniqlik',
                'icon': '🎯🎯',
                'badge_type': 'accuracy',
                'requirement': {'accuracy': 98},
                'xp_reward': 200,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Accuracy King',
                'description': '95%+ o\'rtacha aniqlik',
                'icon': '🎯',
                'badge_type': 'accuracy',
                'requirement': {'accuracy': 95},
                'xp_reward': 100,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Accuracy Master',
                'description': '90%+ o\'rtacha aniqlik',
                'icon': '✅',
                'badge_type': 'accuracy',
                'requirement': {'accuracy': 90},
                'xp_reward': 75,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            
            # Streak badges
            {
                'name': 'Streak Immortal',
                'description': '100 kun ketma-ket mashq qilish',
                'icon': '🔥🔥🔥🔥🔥',
                'badge_type': 'streak',
                'requirement': {'days': 100},
                'xp_reward': 500,
                'rarity': 'legendary',
                'rarity_color': '#ff6b00',
            },
            {
                'name': 'Streak Master',
                'description': '60 kun ketma-ket mashq qilish',
                'icon': '🔥🔥🔥🔥',
                'badge_type': 'streak',
                'requirement': {'days': 60},
                'xp_reward': 300,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Streak Legend',
                'description': '30 kun ketma-ket mashq qilish',
                'icon': '🔥🔥🔥',
                'badge_type': 'streak',
                'requirement': {'days': 30},
                'xp_reward': 200,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Streak Champion',
                'description': '14 kun ketma-ket mashq qilish',
                'icon': '🔥🔥',
                'badge_type': 'streak',
                'requirement': {'days': 14},
                'xp_reward': 100,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Streak Warrior',
                'description': '7 kun ketma-ket mashq qilish',
                'icon': '🔥',
                'badge_type': 'streak',
                'requirement': {'days': 7},
                'xp_reward': 50,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'First Streak',
                'description': '3 kun ketma-ket mashq qilish',
                'icon': '🔥',
                'badge_type': 'streak',
                'requirement': {'days': 3},
                'xp_reward': 25,
                'rarity': 'common',
                'rarity_color': '#6b7280',
            },
            
            # Milestone badges
            {
                'name': 'Ultra Marathon',
                'description': '500 ta mashqni yakunlash',
                'icon': '🏃🏃',
                'badge_type': 'milestone',
                'requirement': {'sessions': 500},
                'xp_reward': 400,
                'rarity': 'legendary',
                'rarity_color': '#ff6b00',
            },
            {
                'name': 'Marathon Runner',
                'description': '100 ta mashqni yakunlash',
                'icon': '🏃',
                'badge_type': 'milestone',
                'requirement': {'sessions': 100},
                'xp_reward': 150,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Century Club',
                'description': '100 ta mashqni yakunlash',
                'icon': '💯',
                'badge_type': 'milestone',
                'requirement': {'sessions': 100},
                'xp_reward': 150,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Dedicated Typist',
                'description': '50 ta mashqni yakunlash',
                'icon': '💪',
                'badge_type': 'milestone',
                'requirement': {'sessions': 50},
                'xp_reward': 75,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'First Steps',
                'description': '10 ta mashqni yakunlash',
                'icon': '👶',
                'badge_type': 'milestone',
                'requirement': {'sessions': 10},
                'xp_reward': 30,
                'rarity': 'common',
                'rarity_color': '#6b7280',
            },
            {
                'name': 'Code Master',
                'description': '100 ta kod mashqini yakunlash',
                'icon': '🥷🥷',
                'badge_type': 'milestone',
                'requirement': {'code_sessions': 100},
                'xp_reward': 200,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Code Ninja',
                'description': '50 ta kod mashqini yakunlash',
                'icon': '🥷',
                'badge_type': 'milestone',
                'requirement': {'code_sessions': 50},
                'xp_reward': 100,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Text Master Pro',
                'description': '100 ta matn mashqini yakunlash',
                'icon': '📝📝',
                'badge_type': 'milestone',
                'requirement': {'text_sessions': 100},
                'xp_reward': 200,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Text Master',
                'description': '50 ta matn mashqini yakunlash',
                'icon': '📝',
                'badge_type': 'milestone',
                'requirement': {'text_sessions': 50},
                'xp_reward': 100,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            
            # Consistency badges
            {
                'name': 'Consistency Legend',
                'description': '100 kun mashq qilish',
                'icon': '📅📅📅',
                'badge_type': 'consistency',
                'requirement': {'practice_days': 100},
                'xp_reward': 400,
                'rarity': 'legendary',
                'rarity_color': '#ff6b00',
            },
            {
                'name': 'Consistency Master',
                'description': '60 kun mashq qilish',
                'icon': '📅📅',
                'badge_type': 'consistency',
                'requirement': {'practice_days': 60},
                'xp_reward': 250,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Consistency Champion',
                'description': '30 kun mashq qilish',
                'icon': '📅',
                'badge_type': 'consistency',
                'requirement': {'practice_days': 30},
                'xp_reward': 150,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Week Warrior',
                'description': '7 kun mashq qilish',
                'icon': '📅',
                'badge_type': 'consistency',
                'requirement': {'practice_days': 7},
                'xp_reward': 50,
                'rarity': 'common',
                'rarity_color': '#6b7280',
            },
            
            # Competition badges
            {
                'name': 'Competition Champion',
                'description': '10 ta musobaqada g\'olib bo\'lish',
                'icon': '👑',
                'badge_type': 'competition',
                'requirement': {'wins': 10},
                'xp_reward': 1000,
                'rarity': 'legendary',
                'rarity_color': '#ff6b00',
            },
            {
                'name': 'Competition Winner',
                'description': 'Musobaqada 1-o\'rinni egallash',
                'icon': '🥇',
                'badge_type': 'competition',
                'requirement': {'first_place': 1},
                'xp_reward': 500,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Competition Runner-up',
                'description': 'Musobaqada 2-o\'rinni egallash',
                'icon': '🥈',
                'badge_type': 'competition',
                'requirement': {'second_place': 1},
                'xp_reward': 300,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Competition Bronze',
                'description': 'Musobaqada 3-o\'rinni egallash',
                'icon': '🥉',
                'badge_type': 'competition',
                'requirement': {'third_place': 1},
                'xp_reward': 200,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Competition Participant',
                'description': '5 ta musobaqada qatnashish',
                'icon': '🏆',
                'badge_type': 'competition',
                'requirement': {'participations': 5},
                'xp_reward': 100,
                'rarity': 'common',
                'rarity_color': '#6b7280',
            },
            
            # Battle badges
            {
                'name': 'Battle Master',
                'description': '10 ta jangda g\'olib bo\'lish',
                'icon': '⚔️',
                'badge_type': 'battle',
                'requirement': {'battle_wins': 10},
                'xp_reward': 200,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Battle Warrior',
                'description': '5 ta jangda g\'olib bo\'lish',
                'icon': '🗡️',
                'badge_type': 'battle',
                'requirement': {'battle_wins': 5},
                'xp_reward': 100,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'First Battle',
                'description': 'Birinchi jangni boshlash',
                'icon': '⚔️',
                'badge_type': 'battle',
                'requirement': {'battles': 1},
                'xp_reward': 25,
                'rarity': 'common',
                'rarity_color': '#6b7280',
            },
            
            # Special achievement badges
            {
                'name': 'Perfect Week',
                'description': 'Bir hafta davomida barcha kunlik vazifalarni bajarish',
                'icon': '⭐',
                'badge_type': 'special',
                'requirement': {'perfect_week': 1},
                'xp_reward': 200,
                'rarity': 'epic',
                'rarity_color': '#9d4edd',
            },
            {
                'name': 'Early Bird',
                'description': 'Kunlik vazifani ertalab bajarish (10 marta)',
                'icon': '🌅',
                'badge_type': 'special',
                'requirement': {'early_completion': 10},
                'xp_reward': 100,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Night Owl',
                'description': 'Kunlik vazifani kechqurun bajarish (10 marta)',
                'icon': '🦉',
                'badge_type': 'special',
                'requirement': {'late_completion': 10},
                'xp_reward': 100,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
            {
                'name': 'Comeback King',
                'description': 'Streak uzilgandan keyin qayta boshlash (5 marta)',
                'icon': '🔄',
                'badge_type': 'special',
                'requirement': {'comebacks': 5},
                'xp_reward': 150,
                'rarity': 'rare',
                'rarity_color': '#3b82f6',
            },
        ]
        
        created_count = 0
        updated_count = 0
        
        for badge_data in badges_data:
            badge, created = Badge.objects.update_or_create(
                name=badge_data['name'],
                defaults={
                    'description': badge_data['description'],
                    'icon': badge_data['icon'],
                    'badge_type': badge_data['badge_type'],
                    'requirement': badge_data['requirement'],
                    'xp_reward': badge_data['xp_reward'],
                    'rarity': badge_data.get('rarity', 'common'),
                    'rarity_color': badge_data.get('rarity_color', '#6b7280'),
                    'is_active': True,
                }
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created badge: {badge.name}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'Updated badge: {badge.name}'))
        
        self.stdout.write(self.style.SUCCESS(
            f'\nBadge creation complete! Created: {created_count}, Updated: {updated_count}'
        ))

