# Generated by Django 6.0 on 2025-12-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('typing_practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='current_stage',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CompetitionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField()),
                ('code_snippet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typing_practice.codesnippet')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='competitions.competition')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='typing_practice.text')),
            ],
            options={
                'ordering': ['stage_number'],
                'unique_together': {('competition', 'stage_number')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionParticipantStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('mistakes', models.IntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='competitions.competitionparticipant')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionstage')),
            ],
            options={
                'ordering': ['stage__stage_number'],
                'unique_together': {('participant', 'stage')},
            },
        ),
    ]
