# Generated by Django 4.2.7 on 2025-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_difficulty_competition_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competitionparticipantstage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competitionstage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='competitionparticipant',
            index=models.Index(fields=['competition', '-result_wpm'], name='competition_competi_9d467c_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionparticipant',
            index=models.Index(fields=['user', 'competition'], name='competition_user_id_dcd39d_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionparticipant',
            index=models.Index(fields=['is_finished', '-result_wpm'], name='competition_is_fini_8c022d_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionparticipantstage',
            index=models.Index(fields=['participant', 'stage'], name='competition_partici_7e3aae_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionparticipantstage',
            index=models.Index(fields=['is_finished', '-wpm'], name='competition_is_fini_dfb4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='competitionstage',
            index=models.Index(fields=['competition', 'stage_number'], name='competition_competi_32ed64_idx'),
        ),
    ]
