# Generated by Django 4.2.7 on 2025-12-10 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_id_alter_competitionparticipant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='max_attempts_per_stage',
            field=models.IntegerField(default=3, help_text='Har bir bosqich uchun maksimal urinishlar soni'),
        ),
        migrations.AddField(
            model_name='competitionparticipantstage',
            name='attempts',
            field=models.IntegerField(default=0, help_text='Bu bosqich uchun urinishlar soni'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competitionparticipant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competitionparticipantstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='competitionstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Sertifikat logosi', null=True, upload_to='certificates/logos/')),
                ('additional_names', models.TextField(blank=True, help_text="Qo'shimcha nomlar (har bir qator alohida)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='competitions.competition')),
            ],
        ),
    ]
