# Generated by Django 4.2.7 on 2025-12-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competition_max_attempts_per_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='enable_certificates',
            field=models.BooleanField(default=False, help_text='Musobaqa tugatilganda sertifikatlar beriladimi?'),
        ),
    ]
