# Generated by Django 4.2.7 on 2025-12-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competition_enable_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_subtitle',
            field=models.CharField(default='Typing Competition Certificate', help_text='Sertifikat pastki sarlavhasi', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='organization_name',
            field=models.CharField(default='GEEKS ANDIJAN', help_text='Tashkilot nomi (sarlavha)', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signature_name',
            field=models.CharField(blank=True, help_text='Imzo nomi (masalan: Geeks Andijan)', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='additional_names',
            field=models.TextField(blank=True, help_text="Qo'shimcha nomlar (har bir qator alohida, footer'da ko'rinadi)"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='logo',
            field=models.ImageField(blank=True, help_text="Sertifikat logosi (yuqorida ko'rinadi)", null=True, upload_to='certificates/logos/'),
        ),
    ]
