# Generated by Django 4.2.7 on 2025-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='codesnippet',
            index=models.Index(fields=['language', 'difficulty'], name='typing_prac_languag_5e62d8_idx'),
        ),
        migrations.AddIndex(
            model_name='text',
            index=models.Index(fields=['difficulty'], name='typing_prac_difficu_59093b_idx'),
        ),
        migrations.AddIndex(
            model_name='userresult',
            index=models.Index(fields=['user', '-time'], name='typing_prac_user_id_773f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='userresult',
            index=models.Index(fields=['session_type', '-time'], name='typing_prac_session_a65e01_idx'),
        ),
        migrations.AddIndex(
            model_name='userresult',
            index=models.Index(fields=['-wpm'], name='typing_prac_wpm_b9e79d_idx'),
        ),
        migrations.AddIndex(
            model_name='userresult',
            index=models.Index(fields=['-time'], name='typing_prac_time_67a3af_idx'),
        ),
    ]
