# Generated by Django 4.2.7 on 2025-12-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_practice', '0002_alter_codesnippet_id_alter_text_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='word_count',
            field=models.IntegerField(choices=[(10, "10 so'z"), (25, "25 so'z"), (60, "60 so'z"), (100, "100 so'z")], default=25, help_text="Matndagi so'zlar soni"),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='text',
            name='body',
            field=models.TextField(help_text="To'liq matn"),
        ),
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(help_text='Qisqa sarlavha', max_length=200),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='text',
            index=models.Index(fields=['difficulty', 'word_count'], name='typing_prac_difficu_0db031_idx'),
        ),
    ]
